// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenHarvest.Infrastructure.Data;

#nullable disable

namespace OpenHarvest.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OpenHarvestDbContext))]
    [Migration("20260425210626_AddCropsTable")]
    partial class AddCropsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenHarvest.Domain.Entities.Crop", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("CanDirectSow")
                        .HasColumnType("boolean");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("DaysToGermination")
                        .HasColumnType("integer");

                    b.Property<int?>("DaysToMaturity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxGrowingZone")
                        .HasColumnType("integer");

                    b.Property<int?>("MinGrowingZone")
                        .HasColumnType("integer");

                    b.Property<double?>("PlantSpacingInches")
                        .HasColumnType("double precision");

                    b.Property<double?>("RowSpacingInches")
                        .HasColumnType("double precision");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Slug");

                    b.HasIndex("CommonName");

                    b.ToTable("crops", (string)null);
                });

            modelBuilder.Entity("OpenHarvest.Domain.Entities.Garden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstFrostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GrowingZone")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastFrostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("gardens", (string)null);
                });

            modelBuilder.Entity("OpenHarvest.Domain.Entities.GardenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Geometry")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Growth")
                        .HasColumnType("jsonb");

                    b.Property<string>("Health")
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Photos")
                        .HasColumnType("jsonb");

                    b.Property<string>("Schedule")
                        .HasColumnType("jsonb");

                    b.Property<string>("Transform")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Yield")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("GardenId", "Kind");

                    b.HasIndex("GardenId", "ModifiedUtc");

                    b.ToTable("garden_entities", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
